# Generated by Django 4.0.1 on 2022-01-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('litr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket',
            new_name='content_author',
        ),
        migrations.AddField(
            model_name='ticket',
            name='content_reference',
            field=models.CharField(default='Val', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='user_comment',
            field=models.CharField(default='Val', max_length=300),
            preserve_default=False,
        ),
    ]
