# Generated by Django 4.0.1 on 2022-01-31 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='content_author',
            field=models.CharField(max_length=80, verbose_name="Nom de l'auteur"),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='content_reference',
            field=models.CharField(max_length=80, verbose_name='Titre de la référence'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user_comment',
            field=models.CharField(max_length=300, verbose_name='Commentaire'),
        ),
    ]
