# Generated by Django 4.0.1 on 2022-01-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_ticket_content_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='user_comment',
            field=models.TextField(max_length=300, verbose_name='Commentaire'),
        ),
    ]
