# Generated by Django 4.0.1 on 2022-01-31 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_review_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='content_picture',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Image'),
        ),
    ]
