# Generated by Django 4.0.1 on 2022-01-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_ticket_content_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='content_picture',
            field=models.ImageField(blank=True, null=True, upload_to='ticket', verbose_name='Image'),
        ),
    ]
