# Generated by Django 4.0.1 on 2022-02-01 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_ticket_content_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='content_author',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name="Nom de l'auteur"),
        ),
        migrations.AddField(
            model_name='review',
            name='content_picture',
            field=models.ImageField(blank=True, null=True, upload_to='ticket', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='review',
            name='content_reference',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Titre de la référence'),
        ),
    ]
