# Generated by Django 4.0.1 on 2022-02-01 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
