# Generated by Django 4.0.1 on 2022-02-02 08:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_review_publication_year_ticket_publication_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='publication_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-400), django.core.validators.MaxValueValidator(2023)], verbose_name='Date de publication'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='publication_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-400), django.core.validators.MaxValueValidator(2023)], verbose_name='Date de publication'),
        ),
    ]
