# Generated by Django 4.0.1 on 2022-02-02 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_rename_time_created_review_review_time_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_time_created',
            new_name='time_created',
        ),
    ]
