# Generated by Django 4.0.1 on 2022-02-02 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_rename_review_time_created_review_time_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-time_created']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-time_created']},
        ),
    ]
