# Generated by Django 4.0.1 on 2022-02-03 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_review_options_alter_ticket_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollows',
        ),
    ]
