# Generated by Django 4.0.1 on 2022-02-04 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_delete_userfollows'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_author',
            new_name='user',
        ),
    ]
