# Generated by Django 4.0.2 on 2022-02-17 09:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_review_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='publication_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-400), django.core.validators.MaxValueValidator(2022)], verbose_name='Date de publication'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='publication_year',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-400), django.core.validators.MaxValueValidator(2022)], verbose_name='Date de publication'),
        ),
    ]
