# Generated by Django 4.0.1 on 2022-02-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_alter_review_rating'),
        ('authentication', '0004_remove_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reviews_list',
            field=models.ManyToManyField(related_name='reviews_list', to='blog.Review'),
        ),
        migrations.AddField(
            model_name='user',
            name='tickets_list',
            field=models.ManyToManyField(related_name='tickets_list', to='blog.Ticket'),
        ),
    ]
